### PR TITLE
[needs-discussion] Figure out app state bucket using aws command instead

### LINKED ISSUE #18: Self determine app state bucket location without having to read public state

### PR DESCRIPTION
**Pull request by limed**
fixes #18

### CODE REVIEW

**Comment by limed** [comment]
I'm wondering if this is an easier way of doing this instead of depending on the public state to exist

**Comment by gozer** [comment]
WE do that kind of stuff at least in one other place IIRC and it makes me cringe.

The issue is the first way is correct. The second approach is a form of heuristic (guessing)

What if an app created a bucket called 

nubis-app-state-voice

For some silly reason?

**Comment by gozer** [comment]
However, I am going to guess you ran into this for a reason. What was going on?

**Comment by limed** [comment]
The discussion was had and a better place to fix this would be in nubisproject/nubis-deploy

**Pull request closed without merging**
